# Generated by Django 3.2.4 on 2021-06-15 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0002_table_dollar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountnumber',
            options={'verbose_name_plural': 'Hisob raqamlar'},
        ),
        migrations.AlterField(
            model_name='table',
            name='employes',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeapp.employees'),
        ),
        migrations.AlterField(
            model_name='table',
            name='monthone',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeapp.months'),
        ),
    ]
