# Generated by Django 3.2.4 on 2021-06-15 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0005_auto_20210615_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='employes',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='financeapp.employees'),
        ),
        migrations.AlterField(
            model_name='table',
            name='monthone',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='financeapp.months'),
        ),
    ]
