# Generated by Django 3.2.4 on 2021-06-16 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0008_auto_20210615_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='employes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeapp.employees'),
        ),
        migrations.AlterField(
            model_name='table',
            name='monthone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeapp.months'),
        ),
    ]
